# Generated by Django 5.0.7 on 2024-07-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
            ],
        ),
    ]
